### ISSUE TITLE
Configuration improvement

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonLimbo#1]
In my opinion, serializing json into json using base64 [is weird and really inconvenient to use](https://0x0.st/sX3m.png).

Maybe that can be improved?

Before you ask: No, I cannot PR this, as I am not good in Go.

Edit: added screenshot

**Comment by skyforce77** [comment]
I could add color codes to create colored text but it would not be as customisable as it is actually. Using directly json into the actual json structure would require to parse the entire structure then reserialize the json message. Do you think that one of those ideas would be better or do you have another one ?

**Comment by mikroskeem** [comment]
> Using directly json into the actual json structure would require to parse the entire structure then reserialize the json message.

Yeah I think that wouldn't be ***that*** good idea.

I think I see why you chose base64 - because putting json into string is even more painful, as user would have to escape quotation marks.

Either way base64 is inconvenient for manual editing. I think I'll proceed with a wrapper which re-writes configuration before starting TyphoonLimbo.

**Comment by IDerr** [comment]
any news on this ?

**Comment by mikroskeem** [comment]
If that helps, I cooked [something like this](https://gist.github.com/mikroskeem/b0d83f3254ce7e6ab45166a64133711f) (not meant for real use, just an example to give directions)

Text formatter (which is not bundled into given gist) pretty much follows the idea of [this library](https://github.com/Janmm14/JsonMessageMaker), configuration file for TyphoonLimbo is generated using [Gson](https://github.com/google/gson), process is executed using [zt-exec](https://github.com/zeroturnaround/zt-exec), and wrapper's configuration file is loaded/serialized using [Configurate](https://github.com/SpongePowered/configurate).
