### ISSUE TITLE
Players with custom entries in game profile cannot join

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonLimbo#11]
I add server-specific data to game profile in BungeeCord to keep some of my systems running slick. But sadly TyphoonLimbo does not seem to like that.

Average (premium player) game profile length ranges from 450-500 characters, my single property adds extra 65 and that causes players unable to login. If I remove textures, then everything works fine (as profile length drops).

Any solutions for that?

**Comment by mikroskeem** [comment]
Relevant log:
```
 2018/02/21 23:33:09 <- 26 &{{"text": "Invalid packet"}}
 2018/02/21 23:33:09 -> 0 &{340  25699 45}
 2018/02/21 23:33:09 Unknown packet #98
 2018/02/21 23:33:09 Unknown packet #100
 2018/02/21 23:33:09 Unknown packet #105
 2018/02/21 23:33:09 Unknown packet #85
 2018/02/21 23:33:09 Unknown packet #76
 2018/02/21 23:33:09 Unknown packet #120
 2018/02/21 23:33:09 Unknown packet #69
 2018/02/21 23:33:09 Unknown packet #71
 2018/02/21 23:33:09 Unknown packet #82
 2018/02/21 23:33:09 Unknown packet #104
 2018/02/21 23:33:09 Unknown packet #82
 2018/02/21 23:33:09 Unknown packet #55
 2018/02/21 23:33:09 Unknown packet #102
 2018/02/21 23:33:09 Unknown packet #100
 2018/02/21 23:33:09 Unknown packet #34
 2018/02/21 23:33:09 127.0.0.1:48027 disconnected.
```

**Comment by skyforce77** [comment]
I don't know how is the data transmitted but I think it's caused by my buffer limitation. Please change the "300" to something like "3000" line 23 of handle_packet.go then recompile.
https://github.com/TyphoonMC/TyphoonLimbo/blob/master/packet_handle.go#L23

**Comment by mikroskeem** [comment]
Yeah that's doable issue solved. Thank you

Could this be exposed on configuration somehow as well though? :smile:

**Comment by skyforce77** [comment]
Nice !
Yes, I'll add it to the config :)

**Comment by skyforce77** [comment]
Added buffer configuration https://github.com/TyphoonMC/TyphoonLimbo/commit/3d9eb3a88c067dfd70354236bbd64bf20b6b6527
