### ISSUE TITLE
Players getting disconnected after 3-4 seconds

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonLimbo#2]
When I run TyphoonLimbo behind BungeeCord(-derivative), player gets disconnected.  
I am using [Waterfall](https://github.com/WaterfallMC/Waterfall) version `This server is running Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160 by md_5`

When I run TyphoonLimbo standalone, it works fine - player does not get disconnected.

TyphoonLimbo log: https://paste.wut.ee/gepifizigu.bash  
Nothing interesting in Waterfall log

**Comment by mikroskeem** [comment]
Apparently this is caused by badly configured HAProxy which sits front of my Waterfall instance. This took a very long time to figure out, sorry :smile: 

Note for other HAProxy users: please read documentation carefully.

**Comment by FixTheAdmin** [comment]
Hmm not sure if this is related but sometimes players get disconnected shortly after joining with "timed out" error

**Comment by mikroskeem** [comment]
Yeah try opening a new issue. Things have changed a lot since I reported this at first place.
