### ISSUE TITLE
Show world to player

### ISSUE THREAD

**Issue by Duartteno** [TyphoonMC/TyphoonLimbo#22]
Hello,
Typhoon has great potential. Would be great if you create way to load the world. 
Are you planning to update typhoon?

**Comment by skyforce77** [comment]
It's planned but I'm not currently able to do it. It takes so much time to study each protocol version to handle maps

**Comment by mrbesen** [comment]
maybe if you create a tool or script to generate a set of packets for each version and store them to json or something. So when a new player connects the player just gets these packets send and done.
The Problem:
ThyphoonLimbo does not support movement at all! So to do it properly you not only need to implement movement and a world but collision and interaction. That would be quite a challenge and would make the Server less lightweight. I think there is a Java-Limbo server somewhere on github, that supports world. check that out.

**Comment by skyforce77** [comment]
Will probably be available at the same time as Minecraft 1.16
[Map implementation](https://github.com/TyphoonMC/TyphoonCore/tree/map)
