### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by jimmyr57000** [TyphoonMC/TyphoonLimbo#24]
Hello,

I have a problem with install Limbo!

go get github.com/TyphoonMC/go.uuid

Nothing is happening
No file is created!

I'am use Debian 9

Thanks you !

**Comment by skyforce77** [comment]
Est-ce que la variable d'environnement GOPATH a bien été configurée ?
Si oui, go get renvoit-il une erreur ?

---

Was GOPATH set up ?
Is go get replying with a error ?

**Comment by skyforce77** [comment]
Peut-être que cette mise à jour corrige un problème de compréhension

https://github.com/TyphoonMC/TyphoonLimbo/commit/b08992285562afb0b3bea3db3413d014eda91c82

**Comment by jimmyr57000** [comment]
Effectivement, la petite mise à jour à résolu mon soucis ^^

Par-contre lors de la connexion avec mon Client 1.8 j'obtiens cela: https://hastebin.com/ikuyehofiq.bash Normal?

Merci !

**Comment by skyforce77** [comment]
C'est normal en mode log, le serveur indique juste qu'il ne connaît pas le paquet envoyé.
TyphoonLimbo n'a pas tous les paquets implémentés, mais ça n'empêche en rien son bon fonctionnement.
