### ISSUE TITLE
.\config.go:27:23: not enough arguments in call to uuid.Must

### ISSUE THREAD

**Issue by MattPuffin** [TyphoonMC/TyphoonLimbo#27]
Im really sorry if this is the wrong place to be posting this. And im really sorry for how useless I am at these sorts of things!

Im using Git to build TyphoonLimbo with the commands listed on the Wiki.
When i do go build I get this error:

$ go build
# TyphoonLimbo
.\config.go:27:23: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)

**Comment by mikroskeem** [comment]
Change
`UUID:     uuid.Must(uuid.NewV4()),`
to
`UUID:     uuid.NewV4(),`

and you're good to go

**Comment by MattPuffin** [comment]
Dude, you're a legend! Sorry I didnt read the pull request!

**Comment by skyforce77** [comment]
Added some tags in go.uuid and TyphoonCore so it shouldn't happen anymore
