### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by wasder** [TyphoonMC/TyphoonLimbo#6]
```
$ go build
# TyphoonLimbo
./config.go:46:24: multiple-value uuid.NewV4() in single-value context

```

**Comment by skyforce77** [comment]
What is your config.json like ?

**Comment by wasder** [comment]
Default one.

**Comment by skyforce77** [comment]
Are you using one of the stable releases or the actual master ?
https://github.com/TyphoonMC/TyphoonLimbo/releases

**Comment by OwnageTechGeek** [comment]
Same error occurs when using stable 1.0.1.

**Comment by wasder** [comment]
Fixed by changing this line 
https://github.com/TyphoonMC/TyphoonLimbo/blob/master/config.go#L46
to
`			uuid:	  uuid.Must(uuid.NewV4()),`

**Comment by OwnageTechGeek** [comment]
Thanks, I'll try it this evening.

**Comment by OwnageTechGeek** [comment]
./connection.go:174:12: invalid operation: config["logs"] (type Config does not support indexing)
./connection.go:207:11: invalid operation: config["logs"] (type Config does not support indexing)
./limbo.go:21:20: invalid operation: config["port"] (type Config does not support indexing)
./packet_handle.go:67:27: invalid operation: config["max_players"] (type Config does not support indexing)
./packet_handle.go:68:16: invalid operation: config["motd"] (type Config does not support indexing)
./packet_handle.go:70:43: invalid operation: config["restricted"] (type Config does not support indexing)
./packet_handle.go:165:27: invalid operation: config["max_players"] (type Config does not support indexing)
./packet_handle.go:167:43: invalid operation: config["restricted"] (type Config does not support indexing)
./packet_registry.go:36:12: invalid operation: config["logs"] (type Config does not support indexing)
[0m

That's the new error I get.

**Comment by skyforce77** [comment]
It was caused by an update of "github.com/satori/go.uuid".
Fixed.
